package me.dakto101.skill;

public enum SkillAttributeType {
	DAMAGE_CAUSE,
	DAMAGE_CAUSE_PERCENT,
	DAMAGE_REDUCTION,
	DAMAGE_REDUCTION_PERCENT,
	MAGIC_CAUSE,
	MAGIC_CAUSE_PERCENT,
	MAGIC_REDUCTION,
	MAGIC_REDUCTION_PERCENT,
	
}
